const COUNTRY_CODES: Record<string, string> = {
	// Africa
	GHANA: "GH",
	NIGERIA: "NG",
	KENYA: "KE",
	"SOUTH AFRICA": "ZA",
	EGYPT: "EG",
	ETHIOPIA: "ET",
	TANZANIA: "TZ",
	UGANDA: "UG",
	RWANDA: "RW",
	SENEGAL: "SN",
	"IVORY COAST": "CI",
	"CÔTE D'IVOIRE": "CI",
	"COTE D'IVOIRE": "CI",
	CAMEROON: "CM",
	ZAMBIA: "ZM",
	ZIMBABWE: "ZW",
	BOTSWANA: "BW",
	NAMIBIA: "NA",
	MOZAMBIQUE: "MZ",
	MALI: "ML",
	GUINEA: "GN",
	BENIN: "BJ",
	TOGO: "TG",
	"BURKINA FASO": "BF",
	"SIERRA LEONE": "SL",
	LIBERIA: "LR",
	GAMBIA: "GM",
	"THE GAMBIA": "GM",
	MAURITIUS: "MU",
	MOROCCO: "MA",
	TUNISIA: "TN",
	ALGERIA: "DZ",
	LIBYA: "LY",
	SUDAN: "SD",
	"SOUTH SUDAN": "SS",
	CHAD: "TD",
	NIGER: "NE",
	LESOTHO: "LS",
	"DEMOCRATIC REPUBLIC OF CONGO": "CD",
	"DR CONGO": "CD",
	DRC: "CD",
	// Americas
	"UNITED STATES": "US",
	USA: "US",
	CANADA: "CA",
	BRAZIL: "BR",
	ARGENTINA: "AR",
	CHILE: "CL",
	COLOMBIA: "CO",
	PERU: "PE",
	MEXICO: "MX",
	VENEZUELA: "VE",
	BOLIVIA: "BO",
	"EL SALVADOR": "SV",
	BAHAMAS: "BS",
	"THE BAHAMAS": "BS",
	// Europe
	"UNITED KINGDOM": "GB",
	UK: "GB",
	GERMANY: "DE",
	FRANCE: "FR",
	PORTUGAL: "PT",
	SPAIN: "ES",
	ITALY: "IT",
	NETHERLANDS: "NL",
	SWEDEN: "SE",
	NORWAY: "NO",
	FINLAND: "FI",
	DENMARK: "DK",
	POLAND: "PL",
	TURKEY: "TR",
	SWITZERLAND: "CH",
	ROMANIA: "RO",
	HUNGARY: "HU",
	LITHUANIA: "LT",
	"BOSNIA AND HERZEGOVINA": "BA",
	"BOSNIA AND HERZOGOVINA": "BA",
	"BOSNIA & HERZEGOVINA": "BA",
	// Middle East
	"SAUDI ARABIA": "SA",
	UAE: "AE",
	"UNITED ARAB EMIRATES": "AE",
	QATAR: "QA",
	JORDAN: "JO",
	LEBANON: "LB",
	// Asia & Oceania
	AUSTRALIA: "AU",
	INDIA: "IN",
	CHINA: "CN",
	JAPAN: "JP",
	PAKISTAN: "PK",
	BANGLADESH: "BD",
	"SRI LANKA": "LK",
	NEPAL: "NP",
	INDONESIA: "ID",
	MALAYSIA: "MY",
	PHILIPPINES: "PH",
	VIETNAM: "VN",
	"VIET NAM": "VN",
	THAILAND: "TH",
	SINGAPORE: "SG",
	"NEW ZEALAND": "NZ",
	"SOUTH KOREA": "KR",
	KOREA: "KR",
	KAZAKHSTAN: "KZ",
};

function toFlagEmoji(code: string): string {
	return [...code.toUpperCase()]
		.map((c) => String.fromCodePoint(c.charCodeAt(0) + 127397))
		.join("");
}

export function getCountryFlag(country: string | null | undefined): string {
	if (!country) return "";
	const upper = country.trim().toUpperCase();
	const code = COUNTRY_CODES[upper];
	if (code) return toFlagEmoji(code);
	if (upper.length === 2) return toFlagEmoji(upper);
	return "";
}
