ALTER TABLE matches ADD COLUMN IF NOT EXISTS scheduled_time_r2 TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS scheduled_time_r3 TIMESTAMPTZ;
ALTER TABLE matches ADD COLUMN IF NOT EXISTS scheduled_time_r4 TIMESTAMPTZ;
